[2024-05-25T08:43:14.211+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T08:43:14.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Deep_Learning_Operator.version manual__2024-05-25T08:43:09.875843+00:00 [queued]>
[2024-05-25T08:43:14.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Deep_Learning_Operator.version manual__2024-05-25T08:43:09.875843+00:00 [queued]>
[2024-05-25T08:43:14.228+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-05-25T08:43:14.232+0000] {taskinstance.py:2330} INFO - Executing <Task(AirflowDeepLearningOperator): version> on 2024-05-25 08:43:09.875843+00:00
[2024-05-25T08:43:14.240+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2654) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-25T08:43:14.241+0000] {standard_task_runner.py:63} INFO - Started process 2656 to run task
[2024-05-25T08:43:14.240+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Deep_Learning_Operator', 'version', 'manual__2024-05-25T08:43:09.875843+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/AirflowDeepLearningPipeline.py', '--cfg-path', '/tmp/tmpdw5a5rw2']
[2024-05-25T08:43:14.242+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask version
[2024-05-25T08:43:14.266+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Deep_Learning_Operator.version manual__2024-05-25T08:43:09.875843+00:00 [running]> on host 41e1ce6ea4b1
[2024-05-25T08:43:14.305+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='synarcs' AIRFLOW_CTX_DAG_ID='Airflow_Deep_Learning_Operator' AIRFLOW_CTX_TASK_ID='version' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T08:43:09.875843+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T08:43:09.875843+00:00'
[2024-05-25T08:43:14.306+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T08:43:14.311+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T08:43:14.311+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/AirflowDeepLearningOperator.py", line 21, in execute
    ops.runner(self.name)
TypeError: AirflowOperatorRunner.runner() takes 1 positional argument but 2 were given
[2024-05-25T08:43:14.317+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Airflow_Deep_Learning_Operator, task_id=version, run_id=manual__2024-05-25T08:43:09.875843+00:00, execution_date=20240525T084309, start_date=20240525T084314, end_date=20240525T084314
[2024-05-25T08:43:14.322+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task version (AirflowOperatorRunner.runner() takes 1 positional argument but 2 were given; 2656)
[2024-05-25T08:43:14.334+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T08:43:14.343+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T08:43:14.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
