[2024-05-25T07:17:02.318+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T07:17:02.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.bash_run manual__2024-05-25T07:17:01.145437+00:00 [queued]>
[2024-05-25T07:17:02.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.bash_run manual__2024-05-25T07:17:01.145437+00:00 [queued]>
[2024-05-25T07:17:02.338+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-05-25T07:17:02.343+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): bash_run> on 2024-05-25 07:17:01.145437+00:00
[2024-05-25T07:17:02.348+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=640) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-25T07:17:02.348+0000] {standard_task_runner.py:63} INFO - Started process 641 to run task
[2024-05-25T07:17:02.348+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'bash_run', 'manual__2024-05-25T07:17:01.145437+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/AirflowDeepLearningOperator.py', '--cfg-path', '/tmp/tmp3v8r7hnq']
[2024-05-25T07:17:02.349+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask bash_run
[2024-05-25T07:17:02.372+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.bash_run manual__2024-05-25T07:17:01.145437+00:00 [running]> on host 803f731ab2bf
[2024-05-25T07:17:02.415+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='synarcs' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='bash_run' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T07:17:01.145437+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T07:17:01.145437+00:00'
[2024-05-25T07:17:02.415+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T07:17:02.433+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-25T07:17:02.434+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'who && ps aux']
[2024-05-25T07:17:02.439+0000] {subprocess.py:86} INFO - Output:
[2024-05-25T07:17:02.444+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: ps: command not found
[2024-05-25T07:17:02.444+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-25T07:17:02.444+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T07:17:02.451+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-25T07:17:02.453+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sample, task_id=bash_run, run_id=manual__2024-05-25T07:17:01.145437+00:00, execution_date=20240525T071701, start_date=20240525T071702, end_date=20240525T071702
[2024-05-25T07:17:02.458+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task bash_run (Bash command failed. The command returned a non-zero exit code 127.; 641)
[2024-05-25T07:17:02.481+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T07:17:02.490+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T07:17:02.491+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
